COMPONENTKIT_PUBLIC_HEADERS = ['ComponentKit/' + x for x in [
  'Accessibility/FBComponentAccessibility.h',
  'Base/CKAssert.h',
  'Base/CKArgumentPrecondition.h',
  'Base/CKMacros.h',
  'Components/FBButtonComponent.h',
  'Components/FBImageComponent.h',
  'Components/FBNetworkImageComponent.h',
  'Components/FBNetworkImageDownloading.h',
  'Core/ComponentLayoutContext.h',
  'Core/ComponentUtilities.h',
  'Core/ComponentViewManager.h',
  'Core/ComponentViewReuseUtilities.h',
  'Core/FBComponent.h',
  'Core/FBComponentAnimation.h',
  'Core/FBComponentAnimationHooks.h',
  'Core/FBComponentBoundsAnimation.h',
  'Core/FBComponentController.h',
  'Core/FBComponentInternal.h',
  'Core/FBComponentLayout.h',
  'Core/FBComponentLifecycleManager.h',
  'Core/FBComponentLifecycleManagerInternal.h',
  'Core/ComponentMountContext.h',
  'Core/FBComponentSize.h',
  'Core/FBComponentSubclass.h',
  'Core/FBComponentViewAttribute.h',
  'Core/FBComponentViewConfiguration.h',
  'Core/FBComponentViewInterface.h',
  'Core/FBCompositeComponent.h',
  'Core/FBDimension.h',
  'Core/Scope/FBComponentScope.h',
  'Core/Scope/FBComponentScopeFrame.h',
  'Core/Scope/FBComponentScopeInternal.h',
  'Core/Scope/FBThreadLocalComponentScope.h',
  'DataSources/Common/FBComponentConstantDecider.h',
  'DataSources/Common/FBComponentDataSource.h',
  'DataSources/Common/FBComponentDataSourceInputItem.h',
  'DataSources/Common/FBComponentDataSourceOutputItem.h',
  'DataSources/Common/FBComponentDeciding.h',
  'DataSources/Common/FBComponentPreparationQueueTypes.h',
  'DataSources/Common/FBComponentPreparationQueue.h',
  'DataSources/Common/FBComponentPreparationQueueInternal.h',
  'DataSources/Common/FBComponentPreparationQueueListener.h',
  'DataSources/Common/FBComponentProvider.h',
  'DataSources/Common/FBSuspensionController.h',
  'DataSources/Common/FBComponentSuspendable.h',
  'DataSources/Common/FBComponentAnnouncerBase.h',
  'DataSources/Common/FBComponentHostingCell.h',
  'DataSources/Common/FBComponentDataSource_RegulatedPreparationQueueExperiment.h',
  'Debug/FBComponentDebugController.h',
  'Debug/FBComponentHierarchyDebugHelper.h',
  'HostingView/FBComponentHostingView.h',
  'HostingView/FBComponentHostingViewDelegate.h',
  'HostingView/FBComponentHostingViewInternal.h',
  'HostingView/FBComponentSizeRangeProviding.h',
  'HostingView/FBComponentFlexibleSizeRangeProvider.h',
  'LayoutComponents/FBBackgroundLayoutComponent.h',
  'LayoutComponents/FBCenterLayoutComponent.h',
  'LayoutComponents/FBInsetComponent.h',
  'LayoutComponents/FBOverlayLayoutComponent.h',
  'LayoutComponents/FBRatioLayoutComponent.h',
  'LayoutComponents/FBStackLayoutComponent.h',
  'LayoutComponents/FBStaticLayoutComponent.h',
  'Utilities/FBComponentAction.h',
  'Utilities/FBComponentContext.h',
  'Utilities/FBComponentContextImpl.h',
  'Utilities/FBComponentGestureActions.h',
  'Utilities/FBOptimisticViewMutations.h',
]]

TEXTKIT_PUBLIC_HEADERS = ['ComponentTextKit/' + x for x in [
  'CKTextComponent.h',
  'CKTextComponentLayer.h',
  'CKTextComponentLayerHighlighter.h',
  'CKTextComponentView.h',
  'CKTextComponentViewControlTracker.h',
  'CKTextComponentViewInternal.h',
  'TextKit/CKTextKitAttributes.h',
  'TextKit/CKTextKitContext.h',
  'TextKit/CKTextKitEntityAttribute.h',
  'TextKit/CKTextKitRenderer.h',
  'TextKit/CKTextKitRenderer+Positioning.h',
  'TextKit/CKTextKitRenderer+TextChecking.h',
  'TextKit/CKTextKitRendererCache.h',
  'TextKit/CKTextKitShadower.h',
  'TextKit/CKTextKitTailTruncater.h',
  'TextKit/CKTextKitTruncating.h',
  'Utility/CKAsyncLayer.h',
  'Utility/CKAsyncLayerInternal.h',
  'Utility/CKAsyncLayerSubclass.h',
  'Utility/CKAsyncTransaction.h',
  'Utility/CKAsyncTransactionContainer.h',
  'Utility/CKAsyncTransactionContainer+Private.h',
  'Utility/CKAsyncTransactionGroup.h',
  'Utility/CKCacheImpl.h',
  'Utility/CKFunctor.h',
  'Utility/CKHighlightOverlayLayer.h',
  'Utility/CKHash.h',
]]

TEXTKIT_SRCS = ['ComponentTextKit/' + x for x in [
  'CKTextComponent.mm',
  'CKTextComponentLayer.mm',
  'CKTextComponentLayerHighlighter.mm',
  'CKTextComponentView.mm',
  'CKTextComponentViewControlTracker.mm',
  'TextKit/CKTextKitAttributes.mm',
  'TextKit/CKTextKitContext.mm',
  'TextKit/CKTextKitRenderer.mm',
  'TextKit/CKTextKitRendererCache.mm',
  'TextKit/CKTextKitRenderer+Positioning.mm',
  'TextKit/CKTextKitRenderer+TextChecking.mm',
  'TextKit/CKTextKitShadower.mm',
  'TextKit/CKTextKitTailTruncater.mm',
  'Utility/CKAsyncLayer.mm',
  'Utility/CKAsyncTransaction.m',
  'Utility/CKAsyncTransactionContainer.m',
  'Utility/CKAsyncTransactionGroup.m',
  'Utility/CKHighlightOverlayLayer.mm',
  'Utility/CKHash.mm',
]]

ios_library(
  name = 'ComponentKit',
  prefix_header = 'ComponentKit/FBComponentKit-Prefix.pch',
  configs = fbobjc_configs(FBOBJC_STATIC_LIBRARY, enable_64bit_builds=True),
  preprocessor_flags = COMMON_PREPROCESSOR_FLAGS,
  header_path_prefix = 'FBComponentKit',
  srcs = TEXTKIT_SRCS + 
    public_headers(*TEXTKIT_PUBLIC_HEADERS) +
    fbsources(
      src_globs=[
        'ComponentKit/**/*.m',
        'ComponentKit/**/*.mm',
      ],
      header_globs=[
        'ComponentKit/**/*.h',
      ],
      public_header_paths=COMPONENTKIT_PUBLIC_HEADERS,
    ),
  tests = [':ComponentKitTests'],
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/CoreGraphics.framework',
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
    '$SDKROOT/System/Library/Frameworks/UIKit.framework',
  ],
  deps = [
    '//Libraries/FBArrayController:FBArrayController',
  ],
  visibility = ['PUBLIC'],
  use_buck_header_maps = True,
)

ios_test(
  name = 'ComponentKitTests',
  test_type = 'xctest',
  prefix_header = 'ComponentKitTests/FBComponentKitTests-Prefix.pch',
  configs = fbobjc_configs(FBOBJC_LOGIC_TESTS, enable_64bit_builds=True, extra_target_config={
    'FB_REFERENCE_IMAGE_DIR' : "\"$(SOURCE_ROOT)/$(PROJECT_NAME)Tests/ReferenceImages\"",
  }),
  info_plist = '//Configurations/Buck/CommonInfoPlists:Test-Info.plist',
  preprocessor_flags = COMMON_PREPROCESSOR_FLAGS,
  srcs = glob([
    'ComponentKitTests/**/*.m',
    'ComponentKitTests/**/*.mm',
    'ComponentKitTests/**/*.h'
    'ComponentTextKitTests/**/*.m',
    'ComponentTextKitTests/**/*.mm',
    'ComponentTextKitTests/**/*.h',
  ]),
  deps = [
    ':ComponentKit',
    ':ComponentKitTestLib',
    '//VendorLib/OCMock:OCMock',
  ],
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
    '$SDKROOT/System/Library/Frameworks/UIKit.framework',
  ],
  use_buck_header_maps = True,
)

COMPONENTKITTESTLIB_PUBLIC_HEADERS = ['ComponentKitTestLib/' + x for x in [
  'CKTestRunLoopRunnning.h',
  'FBComponentDataSourceTestDelegate.h',
  'FBComponentSnapshotTestCase.h',
  'FBComponentTestRootScope.h',
  'FBTestComponentProvider.h',
  'FBTestHeightToggleComponent.h',
  'FBTestComponentDecider.h',
  'FBComponentHostingViewTestModel.h',
]]

ios_library(
  name = 'ComponentKitTestLib',
  prefix_header = 'ComponentKitTestLib/FBComponentKitTestLib-Prefix.pch',
  configs = fbobjc_configs(FBOBJC_STATIC_LIBRARY, enable_64bit_builds=True, extra_target_config={
    'HEADER_SEARCH_PATHS' : '$(inherited) "$(REPO_ROOT)/Vendor/Boost/include"',
    # allow importing from <SenTestingKit/...> $(DEVELOPER_DIR)/Library/Frameworks
    # allow importing from <XCTest/...> $(PLATFORM_DIR)/Developer/Library/Frameworks
    'FRAMEWORK_SEARCH_PATHS' : '$(inherited) "$(DEVELOPER_DIR)/Library/Frameworks" $(PLATFORM_DIR)/Developer/Library/Frameworks',
  }),
  header_path_prefix = 'FBComponentKitTestLib',
  preprocessor_flags = COMMON_PREPROCESSOR_FLAGS,
  srcs = fbsources(
    src_globs=[
      'ComponentKitTestLib/**/*.m',
      'ComponentKitTestLib/**/*.mm',
    ],
    header_globs=[
      'ComponentKitTestLib/**/*.h',
    ],
    public_header_paths=COMPONENTKITTESTLIB_PUBLIC_HEADERS,
  ),
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
    '$SDKROOT/System/Library/Frameworks/UIKit.framework',
    '$SDKROOT/System/Library/Frameworks/QuartzCore.framework',
    '$DEVELOPER_DIR/Library/Frameworks/SenTestingKit.framework',
    '$DEVELOPER_DIR/Library/Frameworks/XCTest.framework',
  ],
  deps = [
    ':ComponentKit',
    '//VendorLib/FBSnapshotTestCase:FBSnapshotTestCase',
  ],
  visibility = ['PUBLIC'],
  use_buck_header_maps = True,
)

fbobjc_xcode_workspace_config(
  name = 'workspace',
  src_target = ':ComponentKit'
)
